# Generated by Django 5.0.4 on 2024-05-07 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=30)),
                ('permit_conduit', models.ImageField(upload_to='documents/')),
            ],
        ),
        migrations.AlterField(
            model_name='categorie',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=100)),
                ('prix_location', models.FloatField()),
                ('prix_vente', models.FloatField()),
                ('annee_fabrication', models.DateField()),
                ('type_de_carburant', models.CharField(max_length=100)),
                ('couleur', models.CharField(max_length=100)),
                ('disponibilite', models.BooleanField(default=True)),
                ('etat', models.CharField(choices=[('neuf', 'Neuf'), ('ocasion', 'Ocasion'), ('louer', 'Louer'), ('vendu', 'Vendu'), ('maintenance', 'Maintenance')], max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vente', models.DateTimeField()),
                ('statut', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.client')),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.voiture')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('statut', models.CharField(choices=[('en-attente', 'En Attente'), ('confirmer', 'Confirmer'), ('annuler', 'Annuler')], max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.client')),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.voiture')),
            ],
        ),
    ]
