# Generated by Django 5.0.4 on 2024-05-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0002_client_alter_categorie_nom_voiture_vente_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='client',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='client',
        ),
        migrations.RemoveField(
            model_name='location',
            name='date_fin',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='date_vente',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='statut',
        ),
        migrations.AddField(
            model_name='location',
            name='adresse',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='email',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='nom',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='permit_conduit',
            field=models.ImageField(default='', null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='location',
            name='prenom',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='telephone',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='total_jours',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='ville',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vente',
            name='adresse',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vente',
            name='email',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vente',
            name='nom',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vente',
            name='prenom',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vente',
            name='telephone',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vente',
            name='ville',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
