# Generated by Django 5.0.4 on 2024-05-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0003_remove_location_client_remove_vente_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='adresse',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='nom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='permit_conduit',
            field=models.ImageField(default='', upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='location',
            name='prenom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='statut',
            field=models.CharField(choices=[('en-attente', 'En Attente'), ('confirmer', 'Confirmer'), ('annuler', 'Annuler')], default='en-attente', max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='telephone',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='total_jours',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='ville',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Vente',
        ),
    ]
