# Generated by Django 5.0.4 on 2024-06-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0004_alter_location_adresse_alter_location_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='date_debut',
            field=models.DateField(),
        ),
    ]
