# Generated by Django 5.0.4 on 2024-06-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0006_alter_location_total_jours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='total_jours',
            field=models.CharField(default='', max_length=50),
        ),
    ]
