# Generated by Django 5.0.4 on 2024-06-04 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0007_alter_location_total_jours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.voiture')),
            ],
        ),
    ]
