# Generated by Django 5.0.4 on 2024-06-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0008_vente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firs_tname', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('adresse_mail', models.CharField(max_length=100)),
                ('mot_de_passe', models.CharField(max_length=100)),
                ('mot_de_passe_confirmation', models.CharField(max_length=100)),
            ],
        ),
    ]
