# Generated by Django 5.0.4 on 2024-06-25 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0009_utilisateur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='firs_tname',
            new_name='first_name',
        ),
    ]
